sudo: required
language: cpp



cache:
  directories:
  - ${APPROXMVBB_CACHE_DIR}

matrix:
  include:
  - env: GCC_VERSION=5 APPROXMVBB_CACHE_DIR="$HOME/ApproxMVBBCache"
    os: linux
    addons: &gcc5
        apt:
          packages:
            - g++-5
          sources:
            - ubuntu-toolchain-r-test

  - env: GCC_VERSION=6 APPROXMVBB_CACHE_DIR="$HOME/ApproxMVBBCache"
    os: linux
    addons: &gcc6
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test

  - env: CLANG_VERSION=5.0 APPROXMVBB_CACHE_DIR="$HOME/ApproxMVBBCache"
    os: linux
    addons: &clang5
        apt:
          packages:
            - util-linux
            - clang-5.0
            - g++-6
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
  - env:
    os: osx
    compiler: clang

# Install dependencies
install:
  - export ROOT_PATH=`pwd`/../;
  - export CHECKOUT_PATH=`pwd`;
  - echo "ROOT_PATH= $ROOT_PATH"
  - echo "CHECKOUT_PATH= $CHECKOUT_PATH"

  - branchName=$(cd $CHECKOUT_PATH && git rev-parse --symbolic-full-name --abbrev-ref HEAD)

  - mkdir -p $APPROXMVBB_CACHE_DIR/{bin,include,lib,share}
  - export CMAKE_PREFIX_PATH="$APPROXMVBB_CACHE_DIR;/usr/local"

  - chmod +x $CHECKOUT_PATH/travis/install_${TRAVIS_OS_NAME}.sh
  - . $CHECKOUT_PATH/travis/install_${TRAVIS_OS_NAME}.sh

before_cache:
  - echo 'Before Caching:' && ls -al $APPROXMVBB_CACHE_DIR

script:
  - chmod +x $CHECKOUT_PATH/travis/build.sh
  - . $CHECKOUT_PATH/travis/build.sh



after_success:
  - cd $CHECKOUT_PATH
  - git reset --hard HEAD # Discard build artifacts
  - git clean -df # Discard build artifacts
  #- bii init -l
  #- bii user $BIICODE_USER -p $BIICODE_PASSWORD
  #- if [ -n "$BIICODE_PASSWORD" ]; then bii publish -r; fi

notifications:
  email: false
